### ISSUE TITLE
ccc/star-rating-bundle dev-master requires fyneworks/star-rating dev-master 

### ISSUE THREAD

**Issue by ajeetvarma** [nurikabe/StarRatingBundle#9]
I tried to install by writting in composer.json as 

"require": {
         "ccc/star-rating-bundle": "dev-master",
         "fyneworks/jquery-star-rating": "dev-master"
   }

and after updating the composer.phar it gives error as 

"ccc/star-rating-bundle dev-master requires fyneworks/star-rating dev-master -> no matching package found."

I do't know what wrong i am doing . Pls help me .

Thanks a lot ..

**Comment by nurikabe** [comment]
Try with the 2.0.0 release:

https://github.com/nurikabe/StarRatingBundle/tree/2.0.0

Note the change in namespace.

**Comment by AyushiSangal** [comment]
Thanks a lot ..

It works fine now ..

**Comment by ajeetvarma** [comment]
Thanks a lot . 

It works fine .
